settings:
  title: '网站运行监控'
  url: 'https://amzm.121723.xyz' # used for Slack messages, 这个不确定是什么用
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 99 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有网站运行正常'
  notAllmonitorsOperational: '部分网站出现问题'
  monitorLabelOperational: '运行正常'
  monitorLabelNotOperational: '运行异常'
  monitorLabelNoData: '暂无数据'
  dayInHistogramNoData: '暂无数据'
  dayInHistogramOperational: '一切正常'
  dayInHistogramNotOperational: ' 事件' # xx incident(s) recorded

monitors:
  - id: bing01 # unique identifier
    name: 网页new bing①
    description: '网友分享的网页new bing， 国内可访问' # default=empty
    url: 'https://bingai.zklcdc.xyz/'
    expectStatus: 403
    followRedirect: true



  - id: bing02 # unique identifier
    name: 网页new bing②
    description: '网友分享的网页new bing， 国内可访问' # default=empty
    url: 'https://bingface.b1ghawk.xyz/'


  - id: bing03 # unique identifier
    name: 网页new bing③
    description: '华沙网页new bing， 国内可访问' # default=empty
    url: 'https://b7.121723.xyz/web/index.html'
    
  - id: bing-self # unique identifier
    name: 网页new bing④
    description: '网页new bing， 国内可访问' # default=empty
    url: 'https://bing.121723.xyz/web/'

  - id: alist # unique identifier
    name: 爱丽丝的咖啡屋
    description: '部署的alist服务，集成了匿名聊天室和一起看功能' # default=empty
    url: 'https://pan.121723.xyz/'

  - id: blog # unique identifier
    name: 爱丽丝的博客
    description: '部署在大善人CF家workers的个人博客' # default=empty
    url: 'https://blog.121723.xyz/'
    
  - id: notify # unique identifier
    name: notify
    description: '部署的notify服务' # default=empty
    url: 'https://ntfy.121723.xyz/'

#  - id: reader # unique identifier
#    name: 在线阅读器
#    description: '计划部署' # default=empty
#    url: 'https://reader.121723.xyz/home'
#    linkable: false
  
#  - id: home # unique identifier
#    name: 🏠
#    description: '此监控和导航页面' # default=empty
#    url: 'https://amzm.121723.xyz/'

#  - id: sd # unique identifier
#    name: stable diffusion
#    description: '又是大善人提供的服务，目前只返回个狗头' # default=empty
#    url: 'https://sd.121723.xyz/'

#  - id: llm # unique identifier
#    name: large language model
#    description: 'CF大善人啊' # default=empty
#    url: 'https://llm.121723.xyz/'

  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: www-cloudflare-com
    name: www.cloudflare.com
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.cloudflare.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: blog-cloudflare-com
    name: The Cloudflare Blog
    url: 'https://blog.cloudflare.com/'
    method: GET
    expectStatus: 200
